Dev
valeriandr411/trello pull request #1
Opened 2023-02-03 12:59 UTC by valeriandr411

2023-02-03 13:52 UTC, ADmitriev99 requested changes
Переделать.

2023-02-03 13:52 UTC, ADmitriev99 commented on pom.xml
> +                <version>2.20</version>
Версии должны быть убраны в переменные

2023-02-03 13:52 UTC, ADmitriev99 commented on pom.xml
> +            <version>0.0.20131108.vaadin1</version>
повторение зависимостей

2023-02-03 13:52 UTC, ADmitriev99 commented on pom.xml
> +        <!-- https://mvnrepository.com/artifact/org.postgresql/postgresql -->
таких комментариев быть не должно

2023-02-03 13:52 UTC, ADmitriev99 commented on src/main/java/check/ApiCheck.java
> +       throw  new OutOfMemoryError("��������������� ������");
два десятка непонятных символов

2023-02-03 13:52 UTC, ADmitriev99 commented on src/main/java/check/ApiCheck.java
> +public class ApiCheck {
что это вообще за класс?

2023-02-03 13:52 UTC, ADmitriev99 commented on src/main/java/check/WebCheck.java
> +    public void test(){}
что это за метод?

2023-02-03 13:52 UTC, ADmitriev99 commented on src/main/java/check/WebCheck.java
> +    public void checkColorInCurrentCard(Color color){
JavaDoc здесь, до и далее

2023-02-03 13:52 UTC, ADmitriev99 commented on src/main/java/check/WebCheck.java
> +        Selenide.sleep(500);
обосновать необходимость использования метода sleep()

2023-02-03 13:52 UTC, ADmitriev99 commented on src/main/java/check/WebCheck.java
> +        SelenideElement colorBlock= $x(".//h4[contains(text(),'Цвета')]/following-sibling::div[1]");
названия переменных должны быть логичны и легко считываемы

2023-02-03 13:52 UTC, ADmitriev99 commented on src/main/java/core/PageManager.java
> +public class PageManager {
лишний класс, который ничего не делает

2023-02-03 13:52 UTC, ADmitriev99 commented on src/main/java/utils/PropertiesUtil.java
> +public final class PropertiesUtil {
Этот класс нужно сделать через синглтон

2023-02-03 13:52 UTC, ADmitriev99 commented on src/main/java/database/ConnectionManager.java
> +    private ConnectionManager(){}
конструктор точно нужен?

2023-02-03 13:52 UTC, ADmitriev99 commented on src/main/java/database/JDBCPostgreSQL.java
> +    public static String getPassword(String login) {
дублирование кода, можно упростить

2023-02-03 13:52 UTC, ADmitriev99 commented on src/main/java/database/JDBCPostgreSQL.java
> +        final String sql = String.format("SELECT * FROM users WHERE login = '%s'", login);
повторяющуюся строку в переменную

2023-02-03 13:52 UTC, ADmitriev99 commented on src/main/java/pages/BoardsPage.java
> +@Deprecated
зачем эта аннотация?

2023-02-03 13:52 UTC, ADmitriev99 commented on src/main/java/pages/BoardsPage.java
> +    private final String addBoardButton = "//div[contains(@class,'board-tile')]";
Три строки можно расположить в любом классе или в enum, отдельный создавать не надо

2023-02-03 13:52 UTC, ADmitriev99 commented on src/main/java/pages/LogInPage.java
> +    // Кнопка войти
комментариев быть не должно

2023-02-03 13:52 UTC, ADmitriev99 commented on src/main/java/pages/LogInPage.java
> +    public void typeEmail(String email) {
подумать над возможностью убрать дублирование

2023-02-03 13:52 UTC, ADmitriev99 commented on src/main/resources/application.properties
> +base.url=
а где?

2023-02-03 13:52 UTC, ADmitriev99 commented on src/main/java/steps/ApiSteps.java
> +    //--------------------------------�����----------------------------------------//
это что-то на французском? к сожалению, я изучаю немецкий

2023-02-03 13:52 UTC, ADmitriev99 commented on src/main/java/steps/ApiSteps.java
> +        Response response = given()
вынести в отдельный метод, убирать дублирование кода

2023-02-03 13:52 UTC, ADmitriev99 commented on src/main/java/steps/ApiSteps.java
> +
пустая строчка?

2023-02-03 13:52 UTC, ADmitriev99 commented on src/main/java/steps/ApiSteps.java
> +        response.prettyPrint();
Зачем вывод? Должен быть написан логгер (здесь, до и после)

2023-02-03 13:52 UTC, ADmitriev99 commented on src/main/java/steps/ApiSteps.java
> +     * �����, ����������� �������� �������� � ��������
Все перевести на литературный английский

2023-02-03 13:52 UTC, ADmitriev99 commented on src/main/java/steps/WebSteps.java
> +    @Step("Нажать на элемент, содержащий текст '{text}' ")
почему здесь есть @Step, а классом выше ее нет?

2023-02-03 13:52 UTC, ADmitriev99 commented on src/test/java/RestTest.java
> +//    @Test
Зачем все эти комментарии?

2023-02-03 13:52 UTC, ADmitriev99 commented on src/test/java/RestTest.java
> +         String idBoard = apiSteps.createBoard("Новая доска для теста");
каждое действие выносится в отдельный метод и обозначается аннотацией @Step

2023-02-03 13:52 UTC, ADmitriev99 commented on src/test/java/RestTest.java
> +//Шаг 13. Поставить в карточке эмоджи Палец вверх
а где сам шаг?

2023-02-03 13:52 UTC, ADmitriev99 commented on src/test/java/RestTest.java
> +        String idListDane = "63c180dfa5dd3f0220c9769a";
это что за Hard-Code-data?

2023-02-03 13:52 UTC, ADmitriev99 commented on src/test/java/RestTest.java
> +    public void after() throws JSONException {
after dark?

2023-02-03 13:52 UTC, ADmitriev99 commented on src/test/java/WebTest.java
> +
Ctrl+Alt+L

2023-02-03 13:52 UTC, ADmitriev99 commented on src/test/java/WebTest.java
> +        webSteps.inputTextInField("������� ����� ����������� �����", login);
вынести тестовые данные в переменные

2023-02-03 13:52 UTC, ADmitriev99 commented on src/test/java/WebTest.java
> +//��� 1. ��������������, ��� �������� ��������� � ������� Done
ниже этой строчки проверок не проводилось

2023-02-10 16:26 UTC, valeriandr411 commented on pom.xml
> +            <version>0.0.20131108.vaadin1</version>
убрала

2023-02-10 16:26 UTC, valeriandr411 commented on pom.xml
> +        <!-- https://mvnrepository.com/artifact/org.postgresql/postgresql -->
убрала

2023-02-10 16:26 UTC, valeriandr411 commented on src/main/java/check/ApiCheck.java
> +       throw  new OutOfMemoryError("��������������� ������");
справила, проблема с кодировкой

2023-03-13 11:44 UTC, closed without merging